---
- name: Set facts for Sysmon variables
  set_fact:
    sysinternals_folder: 'C:\Program Files\sysinternals'
    sysinternals_zip: 'SysinternalsSuite.zip'
    sysmonconfig_file: 'sysmonconfig-export.xml'

- name: Check if Sysinternals folder exists
  win_stat:
    path: "{{ sysinternals_folder }}"
  register: sysinternals_folder_stat

- name: Create Sysinternals folder if it doesn't exist
  win_file:
    path: "{{ sysinternals_folder }}"
    state: directory
  when: not sysinternals_folder_stat.stat.exists

- name: Copy SysinternalsSuite.zip to Windows hosts
  win_copy:
    src: "{{ playbook_dir }}/roles/sysmon_role/SysinternalsSuite.zip"
    dest: "{{ sysinternals_folder }}/{{ sysinternals_zip }}"

- name: Copy sysmonconfig-export.xml to Windows hosts
  win_copy:
    src: "{{ playbook_dir }}/roles/sysmon_role/sysmonconfig-export.xml"
    dest: "{{ sysinternals_folder }}/{{ sysmonconfig_file }}"

- name: Extract Sysinternals Suite
  win_unzip:
    src: "{{ sysinternals_folder }}/{{ sysinternals_zip }}"
    dest: "{{ sysinternals_folder }}"
  when: not sysinternals_folder_stat.stat.exists

- name: Install Sysmon if not already installed (configure registry)
  win_command: "reg.exe ADD HKCU\\Software\\Sysinternals /v EulaAccepted /t REG_DWORD /d 1 /f"
  ignore_errors: yes

- name: Install Sysmon if not already installed (configure registry for HKU\.DEFAULT)
  win_command: "reg.exe ADD HKU\\.DEFAULT\\Software\\Sysinternals /v EulaAccepted /t REG_DWORD /d 1 /f"
  ignore_errors: yes

- name: Install Sysmon if not already installed
  win_shell: "& '{{ sysinternals_folder }}\\Sysmon64.exe' -accepteula -i '{{ sysinternals_folder }}\\{{ sysmonconfig_file }}'"
  ignore_errors: yes
