- name: Download and Install Wazuh Agent
  win_shell: |
    Invoke-WebRequest -Uri {{wazuh_agent_install_package}} -OutFile ${env.tmp}\wazuh-agent; msiexec.exe /i ${env.tmp}\wazuh-agent /q WAZUH_MANAGER='{{ wazuh_manager_host }}' WAZUH_REGISTRATION_SERVER='{{ wazuh_manager_host }}'

- name: Start Wazuh Service
  win_shell: NET START WazuhSvc
