# Aleem Ladha, install exchange server
---
# Add users to the schema and enterprise admin group
- import_playbook: exchangemembership.yml
# Install Exchange Server prerequisites
- import_playbook: exchange_pre.yml
# Install Exchange Server
- import_playbook: exchange_setup.yml
