# LOGS and Monitoring ==========================================================================================

---
- name: Install log agent on windows vms
  hosts: elk_log
  roles:
    - { role: 'logs_windows', tags: 'agent' }

