# LOGS and Monitoring ==========================================================================================

---
- name: Install Sysmon the SOC Fortress way
  hosts: elk_log
  become: yes
  roles:
    - sysmon_role

